### ISSUE TITLE
API Dev Request 4 of 10

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/houseconcierge.com#1]
@codextiny

new microsite: [https://houseconcierge.com/](url)
Credentials:
U: [support@homeowner.ai]
PW: M!l3st0nesL@bs

1.[ Home Page:](https://houseconcierge.com/)

- Update search bar with API functionality

- Add pop up form to Get Started Button in header on home page and Claim my home button on home page

2. [How it Works Page: ](https://houseconcierge.com/how-it-works/)

- Add pop up form to claim my home button in hero image and cta at bottom

**Comment by codextiny** [comment]
@shannonbaldwin 

Done, Please check
